/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface FullMathEchidnaTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): FullMathEchidnaTest;
  clone(): FullMathEchidnaTest;
  methods: {
    checkMulDiv(
      x: number | string | BN,
      y: number | string | BN,
      d: number | string | BN
    ): NonPayableTransactionObject<void>;

    checkMulDivRounding(
      x: number | string | BN,
      y: number | string | BN,
      d: number | string | BN
    ): NonPayableTransactionObject<void>;

    checkMulDivRoundingUp(
      x: number | string | BN,
      y: number | string | BN,
      d: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
