/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface SwapMathTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SwapMathTest;
  clone(): SwapMathTest;
  methods: {
    computeSwapStep(
      sqrtP: number | string | BN,
      sqrtPTarget: number | string | BN,
      liquidity: number | string | BN,
      amountRemaining: number | string | BN,
      feePips: number | string | BN
    ): NonPayableTransactionObject<{
      sqrtQ: string;
      amountIn: string;
      amountOut: string;
      feeAmount: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    getGasCostOfComputeSwapStep(
      sqrtP: number | string | BN,
      sqrtPTarget: number | string | BN,
      liquidity: number | string | BN,
      amountRemaining: number | string | BN,
      feePips: number | string | BN
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
