/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface TickBitmapTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): TickBitmapTest;
  clone(): TickBitmapTest;
  methods: {
    bitmap(arg0: number | string | BN): NonPayableTransactionObject<string>;

    flipTick(tick: number | string | BN): NonPayableTransactionObject<void>;

    getGasCostOfFlipTick(
      tick: number | string | BN
    ): NonPayableTransactionObject<string>;

    getGasCostOfNextInitializedTickWithinOneWord(
      tick: number | string | BN,
      lte: boolean
    ): NonPayableTransactionObject<string>;

    isInitialized(
      tick: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    nextInitializedTickWithinOneWord(
      tick: number | string | BN,
      lte: boolean
    ): NonPayableTransactionObject<{
      next: string;
      initialized: boolean;
      0: string;
      1: boolean;
    }>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
