/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface TickMathTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): TickMathTest;
  clone(): TickMathTest;
  methods: {
    MAX_SQRT_RATIO(): NonPayableTransactionObject<string>;

    MIN_SQRT_RATIO(): NonPayableTransactionObject<string>;

    getGasCostOfGetSqrtRatioAtTick(
      tick: number | string | BN
    ): NonPayableTransactionObject<string>;

    getGasCostOfGetTickAtSqrtRatio(
      sqrtPriceX96: number | string | BN
    ): NonPayableTransactionObject<string>;

    getSqrtRatioAtTick(
      tick: number | string | BN
    ): NonPayableTransactionObject<string>;

    getTickAtSqrtRatio(
      sqrtPriceX96: number | string | BN
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
