/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface TickOverflowSafetyEchidnaTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): TickOverflowSafetyEchidnaTest;
  clone(): TickOverflowSafetyEchidnaTest;
  methods: {
    increaseFeeGrowthGlobal0X128(
      amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    increaseFeeGrowthGlobal1X128(
      amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    moveToTick(target: number | string | BN): NonPayableTransactionObject<void>;

    setPosition(
      tickLower: number | string | BN,
      tickUpper: number | string | BN,
      liquidityDelta: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
