/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface UniswapV3PoolSwapTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): UniswapV3PoolSwapTest;
  clone(): UniswapV3PoolSwapTest;
  methods: {
    getSwapResult(
      pool: string,
      zeroForOne: boolean,
      amountSpecified: number | string | BN,
      sqrtPriceLimitX96: number | string | BN
    ): NonPayableTransactionObject<{
      amount0Delta: string;
      amount1Delta: string;
      nextSqrtRatio: string;
      0: string;
      1: string;
      2: string;
    }>;

    uniswapV3SwapCallback(
      amount0Delta: number | string | BN,
      amount1Delta: number | string | BN,
      data: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
