/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface OracleEchidnaTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): OracleEchidnaTest;
  clone(): OracleEchidnaTest;
  methods: {
    advanceTime(by: number | string | BN): NonPayableTransactionObject<void>;

    checkTimeWeightedAveragesAlwaysFitsType(
      secondsAgo: number | string | BN
    ): NonPayableTransactionObject<void>;

    checkTwoAdjacentObservationsTickCumulativeModTimeElapsedAlways0(
      index: number | string | BN
    ): NonPayableTransactionObject<void>;

    echidna_AlwaysInitialized(): NonPayableTransactionObject<boolean>;

    echidna_canAlwaysObserve0IfInitialized(): NonPayableTransactionObject<boolean>;

    echidna_cardinalityAlwaysLteNext(): NonPayableTransactionObject<boolean>;

    echidna_indexAlwaysLtCardinality(): NonPayableTransactionObject<boolean>;

    grow(cardinality: number | string | BN): NonPayableTransactionObject<void>;

    initialize(
      time: number | string | BN,
      tick: number | string | BN,
      liquidity: number | string | BN
    ): NonPayableTransactionObject<void>;

    update(
      advanceTimeBy: number | string | BN,
      tick: number | string | BN,
      liquidity: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
