#!/usr/bin/env node
import seq from './sequelize';
import * as SeqModel from './model/seqModel/0_index';
import * as DBModel from './model/dbModel/0_index';
import { TransactionStatus } from './model/dbModel/Transaction';
import {
  CustomerContractStatus,
  CustomerStatus,
} from './model/dbModel/Customer';
import { AgentStatus } from './model/dbModel/Agent';
import { BalanceStatus } from './model/dbModel/Balance';
import {
  BalanceHistoryStatus,
  BalanceHistoryTypes,
} from './model/dbModel/BalanceHistory';
import { PriceHistoryStatus } from './model/dbModel/PriceHistory';
import { CustomerCreditUpdateStatus } from './model/dbModel/CustomerCreditUpdate';
import { InterestHistoryStatus } from './model/dbModel/InterestHistory';
import PriceHistoryRef from './model/dbModel/PriceHistoryRef';
import moment from 'moment';
import fs from 'fs';
import path from 'path';
import sqlFuncs from './script/sqlFunctions/SQLFunctions';
import logger from './util/ServiceLogger';
import { CommissionJobStatus } from './model/dbModel/CommissionJob';
import { CommissionDistributionStatus } from './model/dbModel/CommissionDistribution';
import { CronJobStatus, CronJobType } from './model/dbModel/CronJob';
import globalVar from './const/globalVar';
import { MstPrice } from './model/dbModel/0_index';
import { MstPriceStatus } from './model/dbModel/MstPrice';
export async function createSqlFunction(): Promise<void> {
  for (let i = 0; i < sqlFuncs.length; i++) {
    try {
      await seq.sequelize.query(sqlFuncs[i].sql);
    } catch (e) {
      logger.error(e);
    }
  }
}
export async function removeSqlFunction(): Promise<void> {
  for (let i = 0; i < sqlFuncs.length; i++) {
    try {
      await seq.sequelize.query(`DROP FUNCTION IF EXISTS ${sqlFuncs[i].name};`);
    } catch (e) {
      logger.error(e);
    }
  }
}
export async function resetTable(): Promise<void> {
  console.log('seq: ', seq);
  const dateNow = new Date();
  const testDate = moment('2021-09-11').startOf('day').toDate();
  await seq.assertDatabaseConnectionOk();
  const modelModule = seq.sequelize.models;
  await removeSqlFunction();
  await seq.sequelize.drop();
  await seq.sequelize.sync({ force: true });
  const dummyPrices: DBModel.Prices[] = [
    {
      pairName: 'ETHM/USDM',
      reserve0: '9086175534189845267823773',
      reserve1: '36226355949503108',
      createdDate: new Date(),
    },
    {
      pairName: 'BTCM/USDM',
      reserve0: '492033094183621870992750',
      reserve1: '23431875995413998',
      createdDate: new Date(),
    },
  ];
  //Agent
  const dummyAgents: DBModel.Agent[] = [
    {
      //1
      id: null,
      address: '0xabaf0503d06ac5d222653f3294a134db3ca98e29',
      name: '1',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '1@gmail.com',
      parentAgentId: null,
      interestPercentage: 100,
      feePercentage: 100,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: null,
      signData:
        '{"id":"39","address":"0xabaf0503d06ac5d222653f3294a134db3ca98e29"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //2
      id: null,
      address: '0x227460d406f0937ecd982b20cfff5a92e7fc4c2b',
      name: '2',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '2@gmail.com',
      parentAgentId: 1,
      interestPercentage: 50,
      feePercentage: 50,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: null,
      signData:
        '{"id":"4","address":"0x227460d406f0937ecd982b20cfff5a92e7fc4c2b"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //3
      id: null,
      address: '0xc316a94074fe5c387d6099e286e7f05a4dfc599f',
      name: '3',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '3@gmail.com',
      parentAgentId: 1,
      interestPercentage: 40,
      feePercentage: 40,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: null,
      signData:
        '{"id":"23","address":"0xc316a94074fe5c387d6099e286e7f05a4dfc599f"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //4
      id: null,
      address: '0xf4352e40e900207ce9fa992957d457be5423c855',
      name: '4',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '4@gmail.com',
      parentAgentId: 2,
      interestPercentage: 30,
      feePercentage: 30,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: null,
      signData:
        '{"id":"24","address":"0xf4352e40e900207ce9fa992957d457be5423c855"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //5
      id: null,
      address: '0x7b78b035b6511038b1e9d31240a253b0003783d5',
      name: '5',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '5@gmail.com',
      parentAgentId: 2,
      interestPercentage: 30,
      feePercentage: 30,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: null,
      signData:
        '{"id":"38","address":"0x7b78b035b6511038b1e9d31240a253b0003783d5"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //6
      id: null,
      address: '0xe62fb071848d892b01924a8f089555e898522bf9',
      name: '6',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '6@gmail.com',
      parentAgentId: 4,
      interestPercentage: 20,
      feePercentage: 20,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: null,
      signData:
        '{"id":"37","address":"0xe62fb071848d892b01924a8f089555e898522bf9"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //7
      id: null,
      address: '0x4dfb6d6790054f3eb68324bc230e3104137ca8db',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '7@gmail.com',
      parentAgentId: 5,
      interestPercentage: 20,
      feePercentage: 20,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"2","address":"0x4dfb6d6790054f3eb68324bc230e3104137ca8db"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //8
      id: null,
      address: '0x4dfb6d6790054f3eb68324bc230e3104137ca8d1',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '8@gmail.com',
      parentAgentId: 3,
      interestPercentage: 40,
      feePercentage: 40,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"8","address":"0x4dfb6d6790054f3eb68324bc230e3104137ca8d1"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //9
      id: null,
      address: '0x4dfb6d6790054f3eb68324bc230e3104137ca8d2',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '9@gmail.com',
      parentAgentId: 3,
      interestPercentage: 30,
      feePercentage: 30,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"9","address":"0x4dfb6d6790054f3eb68324bc230e3104137ca8d2"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //10
      id: null,
      address: '0x4dfb6d6790054f3eb68324bc230e3104137ca8d3',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '10@gmail.com',
      parentAgentId: 8,
      interestPercentage: 10,
      feePercentage: 10,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"10","address":"0x4dfb6d6790054f3eb68324bc230e3104137ca8d3"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //11
      id: null,
      address: '0x4dfb6d6790054f3eb68324bc230e3104137ca8d4',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '11@gmail.com',
      parentAgentId: 9,
      interestPercentage: 20,
      feePercentage: 20,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 0,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"11","address":"0x4dfb6d6790054f3eb68324bc230e3104137ca8d4"}',
      allowViewAgent: false,
      parentTree: [],
    },
  ];

  const dummyAgents2: DBModel.Agent[] = [
    {
      //12
      id: null,
      address: '0xf4352e40e900207ce9fa992957d457be5423c812',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '12@gmail.com',
      parentAgentId: 1,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"12","address":"0xf4352e40e900207ce9fa992957d457be5423c812"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //13
      id: null,
      address: '0x7b78b035b6511038b1e9d31240a253b0003783d2',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '13@gmail.com',
      parentAgentId: 12,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"13","address":"0x7b78b035b6511038b1e9d31240a253b0003783d2"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //14
      id: null,
      address: '0xe62fb071848d892b01924a8f089555e898522bf4',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '14@gmail.com',
      parentAgentId: 12,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"14","address":"0xe62fb071848d892b01924a8f089555e898522bf4"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //15
      id: null,
      address: '0x192107206e23694d8677325e1647248baf7b67af',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '15@gmail.com',
      parentAgentId: 13,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"15","address":"0x192107206e23694d8677325e1647248baf7b67af"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //16
      id: null,
      address: '0xecbdbe7df4e036421fffbe01bf092f012c2cd589',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '16@gmail.com',
      parentAgentId: 13,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"16","address":"0xecbdbe7df4e036421fffbe01bf092f012c2cd589"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //17
      id: null,
      address: '0x6542e0944aaf2b79a810ab6fda5b9d9058ccec18',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '17@gmail.com',
      parentAgentId: 15,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"17","address":"0x6542e0944aaf2b79a810ab6fda5b9d9058ccec18"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //18
      id: null,
      address: '0xfa685ada16ce7b036a29d8473b019a33b5c65c68',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '18@gmail.com',
      parentAgentId: 16,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"18","address":"0xfa685ada16ce7b036a29d8473b019a33b5c65c68"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //19
      id: null,
      address: '0x4e0746e4af1cc119e0301335df5cbc71291c554a',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '19@gmail.com',
      parentAgentId: 14,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"19","address":"0x4e0746e4af1cc119e0301335df5cbc71291c554a"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //20
      id: null,
      address: '0x32970b2d7afb8460c22753a486710e188a3f77da',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '20@gmail.com',
      parentAgentId: 14,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"20","address":"0x32970b2d7afb8460c22753a486710e188a3f77da"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //21
      id: null,
      address: '0x099175feaf19bf97e2b876877233959c7be1bd48',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '21@gmail.com',
      parentAgentId: 19,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"21","address":"0x099175feaf19bf97e2b876877233959c7be1bd48"}',
      allowViewAgent: false,
      parentTree: [],
    },
    {
      //22
      id: null,
      address: '0xe9a4c00b208bbd44dfe8d263ce906b0ed2e370cd',
      name: 'the verifier',
      password:
        '0x48bed44d1bcd124a28c27f343a817e5f5243190d3c52bf347daf876de1dbbf77',
      email: '22@gmail.com',
      parentAgentId: 20,
      interestPercentage: 0,
      feePercentage: 0,
      referralCodeId: null,
      fundingCodeId: null,
      agentType: 2,
      agentLevel: 0,
      createdDate: dateNow,
      createdById: 0,
      lastModifiedDate: dateNow,
      lastModifiedById: 0,
      status: AgentStatus.StatusActive,
      role: 'account',
      signData:
        '{"id":"22","address":"0xe9a4c00b208bbd44dfe8d263ce906b0ed2e370cd"}',
      allowViewAgent: false,
      parentTree: [],
    },
  ];
  const dummyTokens: DBModel.Token[] = [
    {
      id: null,
      name: 'BTCM',
      address:
        globalVar.foundationConfig.smartcontract.MappedSwap[
          'OwnedBeaconProxy<BTCM>'
        ].address,
      decimals: 18,
    },
    {
      id: null,
      name: 'ETHM',
      address:
        globalVar.foundationConfig.smartcontract.MappedSwap[
          'OwnedBeaconProxy<ETHM>'
        ].address,
      decimals: 18,
    },
    {
      id: null,
      name: 'USDM',
      address:
        globalVar.foundationConfig.smartcontract.MappedSwap[
          'OwnedBeaconProxy<USDM>'
        ].address,
      decimals: 6,
    },
    {
      id: null,
      name: 'MST',
      address:
        globalVar.foundationConfig.smartcontract.MappedSwap[
          'OwnedBeaconProxy<MST>'
        ].address,
      decimals: 18,
    },
  ];

  const dummyCustomers: DBModel.Customer[] = [
    {
      id: null,
      address: '0xd1abc154B43368b8B0B960fA9Ab84545cA1cf816',
      name: 'abc',
      agentId: 1,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324355',
      name: 'abc',
      agentId: 2,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324342',
      name: 'abc',
      agentId: 3,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324343',
      name: 'abc',
      agentId: 4,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324344',
      name: 'abc',
      agentId: 5,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324345',
      name: 'abc',
      agentId: 6,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324346',
      name: 'abc',
      agentId: 7,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324347',
      name: 'abc',
      agentId: 8,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324348',
      name: 'abc',
      agentId: 9,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324351',
      name: 'abc',
      agentId: 10,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324352',
      name: 'abc',
      agentId: 11,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
  ];
  const dummyCustomers2: DBModel.Customer[] = [
    {
      id: null,
      address: '0xd1abc154b43368b8b0b960fa9ab84545ca1cf831',
      name: 'abc',
      agentId: 12,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324332',
      name: 'abc',
      agentId: 13,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324333',
      name: 'abc',
      agentId: 14,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324334',
      name: 'abc',
      agentId: 15,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324335',
      name: 'abc',
      agentId: 16,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324336',
      name: 'abc',
      agentId: 17,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324337',
      name: 'abc',
      agentId: 18,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324338',
      name: 'abc',
      agentId: 19,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7D26e342DGe234324FEgfd345435gF34f4H4324339',
      name: 'abc',
      agentId: 20,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324340',
      name: 'abc',
      agentId: 21,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324341',
      name: 'abc',
      agentId: 22,
      leverage: 10000,
      maxFunding: 2000000000 * 1000000,
      creditMode: 0,
      contractStatus: CustomerContractStatus.StatusEnabled,
      riskLevel: 100,
      fundingCodeId: 0,
      type: 0,
      createdDate: dateNow,
      createdById: null,
      lastModifiedDate: dateNow,
      lastModifiedById: null,
      status: CustomerStatus.StatusActive,
    },
  ];

  //DApp
  const dummyAgentDailyReports: DBModel.AgentDailyReport[] = [];
  const dummyBalances: DBModel.Balance[] = [
    {
      id: null,
      address: '0xd1abc154b43368b8b0b960fa9ab84545ca1cf816',
      customerId: 1,
      agentId: 1,
      token: 'BTCM',
      balance: -2000,
      interest: 0,
      updateTime: new Date(),
      status: BalanceStatus.StatusActive,
    },
    {
      id: null,
      address: '0xd1abc154B43368b8B0B960fA9Ab84545cA1cf816',
      customerId: 1,
      agentId: 1,
      token: 'ETHM',
      balance: -200,
      interest: 0,
      updateTime: new Date(),
      status: BalanceStatus.StatusActive,
    },
    {
      id: null,
      address: '0xd1abc154b43368b8b0b960fa9ab84545ca1cf816',
      customerId: 1,
      agentId: 1,
      token: 'USDM',
      balance: 20,
      interest: 0,
      updateTime: new Date(),
      status: BalanceStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324355',
      customerId: 2,
      agentId: 2,
      token: 'BTCM',
      balance: -500,
      interest: 0,
      updateTime: new Date(),
      status: BalanceStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324355',
      customerId: 2,
      agentId: 2,
      token: 'ETHM',
      balance: -50,
      interest: 0,
      updateTime: new Date(),
      status: BalanceStatus.StatusActive,
    },
    {
      id: null,
      address: '2x7d26e342dge234324fegfd345435gf34f4h4324355',
      customerId: 2,
      agentId: 2,
      token: 'USDM',
      balance: 50,
      interest: 0,
      updateTime: new Date(),
      status: BalanceStatus.StatusActive,
    },
  ];
  const dummyPriceHistories: DBModel.PriceHistory[] = [];

  const dummyPRiceHistoriesRefs: DBModel.PriceHistoryRef[] = [];

  const dummyPrice: DBModel.Prices[] = [];

  const dummyCronJobs: DBModel.CronJob[] = [];

  const dummyCommissionJobs: DBModel.CommissionJob[] = [];
  const dummyCommissionSummaries: DBModel.CommissionSummary[] = [];
  const dummyInterestHistories: DBModel.InterestHistory[] = [
    {
      id: null,
      address: '',
      customerId: 1,
      agentId: 1,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 1000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 2,
      agentId: 2,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 2000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 4,
      agentId: 4,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 1000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 4,
      agentId: 4,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 2000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 6,
      agentId: 6,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 1000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 6,
      agentId: 6,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 4000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 5,
      agentId: 5,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 2000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 5,
      agentId: 5,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 4000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 7,
      agentId: 7,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 300000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 7,
      agentId: 7,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 4000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },

    {
      id: null,
      address: '',
      customerId: 3,
      agentId: 3,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 4000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 8,
      agentId: 8,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 150000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 8,
      agentId: 8,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 240000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 9,
      agentId: 9,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 100000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 9,
      agentId: 9,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 20000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 10,
      agentId: 10,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 3000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 10,
      agentId: 10,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 400000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 11,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 300000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 11,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 250000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 10,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 2000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
  ];
  const dummyInterestHistoriesType2: DBModel.InterestHistory[] = [
    {
      id: null,
      address: '',
      customerId: 12,
      agentId: 12,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 1000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    // {
    //   id: null,
    //   address: '',
    //   customerId: 13,
    //   agentId: 13,
    //   fromTime: new Date(),
    //   toTime: new Date(),
    //   token: 'USDM',
    //   amount: 0,
    //   rate: 0,
    //   interest: 2000000000,
    //   totalInterest: 0,
    //   createdDate: moment('2021-12-31').startOf('day').toDate(),
    //   lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    //   status: InterestHistoryStatus.StatusPending,
    // },
    {
      id: null,
      address: '',
      customerId: 15,
      agentId: 15,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 1000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 15,
      agentId: 15,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 2000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 17,
      agentId: 17,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 1000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 17,
      agentId: 17,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 4000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    // {
    //   id: null,
    //   address: '',
    //   customerId: 16,
    //   agentId: 16,
    //   fromTime: new Date(),
    //   toTime: new Date(),
    //   token: 'USDM',
    //   amount: 0,
    //   rate: 0,
    //   interest: 2000000000,
    //   totalInterest: 0,
    //   createdDate: moment('2021-12-31').startOf('day').toDate(),
    //   lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    //   status: InterestHistoryStatus.StatusPending,
    // },
    // {
    //   id: null,
    //   address: '',
    //   customerId: 16,
    //   agentId: 16,
    //   fromTime: new Date(),
    //   toTime: new Date(),
    //   token: 'USDM',
    //   amount: 0,
    //   rate: 0,
    //   interest: 4000000000,
    //   totalInterest: 0,
    //   createdDate: moment('2021-12-31').startOf('day').toDate(),
    //   lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    //   status: InterestHistoryStatus.StatusPending,
    // },
    // {
    //   id: null,
    //   address: '',
    //   customerId: 18,
    //   agentId: 18,
    //   fromTime: new Date(),
    //   toTime: new Date(),
    //   token: 'USDM',
    //   amount: 0,
    //   rate: 0,
    //   interest: 3000000000,
    //   totalInterest: 0,
    //   createdDate: moment('2021-12-31').startOf('day').toDate(),
    //   lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    //   status: InterestHistoryStatus.StatusPending,
    // },
    // {
    //   id: null,
    //   address: '',
    //   customerId: 18,
    //   agentId: 18,
    //   fromTime: new Date(),
    //   toTime: new Date(),
    //   token: 'USDM',
    //   amount: 0,
    //   rate: 0,
    //   interest: 4000000000,
    //   totalInterest: 0,
    //   createdDate: moment('2021-12-31').startOf('day').toDate(),
    //   lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    //   status: InterestHistoryStatus.StatusPending,
    // },

    {
      id: null,
      address: '',
      customerId: 14,
      agentId: 14,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 4000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 19,
      agentId: 19,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 150000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 19,
      agentId: 19,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 240000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 20,
      agentId: 20,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 100000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 20,
      agentId: 20,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 20,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 21,
      agentId: 21,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 3000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 21,
      agentId: 21,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 400000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 22,
      agentId: 22,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 300000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 22,
      agentId: 22,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 250000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 21,
      fromTime: new Date(),
      toTime: new Date(),
      token: 'USDM',
      amount: 0,
      rate: 0,
      interest: 2000000000,
      totalInterest: 0,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
      status: InterestHistoryStatus.StatusActive,
    },
  ];
  const dummyTransactions: DBModel.Transaction[] = [
    {
      id: null,
      address: '',
      customerId: 1,
      agentId: 1,
      sellToken: 'USDM',
      sellAmount: 1000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 1,
      agentId: 1,
      sellToken: 'BTCM',
      sellAmount: 50153084518416174000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 2,
      agentId: 2,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 4,
      agentId: 4,
      sellToken: 'USDM',
      sellAmount: 1000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 4,
      agentId: 4,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 6,
      agentId: 6,
      sellToken: 'USDM',
      sellAmount: 1000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 6,
      agentId: 6,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 5,
      agentId: 5,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 5,
      agentId: 5,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 7,
      agentId: 7,
      sellToken: 'USDM',
      sellAmount: 3000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 7,
      agentId: 7,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },

    {
      id: null,
      address: '',
      customerId: 3,
      agentId: 3,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 8,
      agentId: 8,
      sellToken: 'USDM',
      sellAmount: 150000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 8,
      agentId: 8,
      sellToken: 'USDM',
      sellAmount: 240000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 9,
      agentId: 9,
      sellToken: 'USDM',
      sellAmount: 100000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 9,
      agentId: 9,
      sellToken: 'USDM',
      sellAmount: 20000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 10,
      agentId: 10,
      sellToken: 'USDM',
      sellAmount: 3000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 10,
      agentId: 10,
      sellToken: 'USDM',
      sellAmount: 400000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 11,
      sellToken: 'USDM',
      sellAmount: 300000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 11,
      sellToken: 'USDM',
      sellAmount: 250000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 10,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
  ];

  const dummyTransactionsType2: DBModel.Transaction[] = [
    {
      id: null,
      address: '',
      customerId: 12,
      agentId: 12,
      sellToken: 'USDM',
      sellAmount: 1000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 12,
      agentId: 12,
      sellToken: 'BTCM',
      sellAmount: 50153084518416174000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 13,
      agentId: 13,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 15,
      agentId: 15,
      sellToken: 'USDM',
      sellAmount: 1000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 15,
      agentId: 15,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 17,
      agentId: 17,
      sellToken: 'USDM',
      sellAmount: 1000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 17,
      agentId: 17,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 16,
      agentId: 16,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 16,
      agentId: 16,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 18,
      agentId: 18,
      sellToken: 'USDM',
      sellAmount: 3000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 18,
      agentId: 18,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },

    {
      id: null,
      address: '',
      customerId: 14,
      agentId: 14,
      sellToken: 'USDM',
      sellAmount: 4000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 19,
      agentId: 19,
      sellToken: 'USDM',
      sellAmount: 150000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 19,
      agentId: 19,
      sellToken: 'USDM',
      sellAmount: 240000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 20,
      agentId: 20,
      sellToken: 'USDM',
      sellAmount: 100000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 20,
      agentId: 20,
      sellToken: 'USDM',
      sellAmount: 20000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 21,
      agentId: 21,
      sellToken: 'USDM',
      sellAmount: 3000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 21,
      agentId: 21,
      sellToken: 'USDM',
      sellAmount: 400000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 22,
      agentId: 22,
      sellToken: 'USDM',
      sellAmount: 300000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 22,
      agentId: 22,
      sellToken: 'USDM',
      sellAmount: 250000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
    {
      id: null,
      address: '',
      customerId: 11,
      agentId: 21,
      sellToken: 'USDM',
      sellAmount: 2000000000,
      buyToken: '',
      buyAmount: 0,
      txHash: '',
      txTime: moment('2021-12-31').startOf('day').toDate(),
      txStatus: TransactionStatus.Confirmed,
      gasFee: 0,
      blockHeight: 0,
      blockHash: '',
      stopout: false,
      createdDate: moment('2021-12-31').startOf('day').toDate(),
      lastModifiedDate: moment('2021-12-31').startOf('day').toDate(),
    },
  ];
  const dummyDistRuleMists: DBModel.MSTDistRule[] = [
    {
      id: null,
      grade: 1,
      weekAmount: 60000000000000,
      holdMST: 20000000000000000000000000,
      commissionRate: 80,
      distMTokenRate: 40,
      distMSTTokenRate: 40,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 2,
      weekAmount: 30000000000000,
      holdMST: 8000000000000000000000000,
      commissionRate: 70,
      distMTokenRate: 35,
      distMSTTokenRate: 35,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 3,
      weekAmount: 15000000000000,
      holdMST: 2000000000000000000000000,
      commissionRate: 60,
      distMTokenRate: 30,
      distMSTTokenRate: 30,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 4,
      weekAmount: 7500000000000,
      holdMST: 800000000000000000000000,
      commissionRate: 52,
      distMTokenRate: 26,
      distMSTTokenRate: 26,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 5,
      weekAmount: 3000000000000,
      holdMST: 200000000000000000000000,
      commissionRate: 45,
      distMTokenRate: 22.5,
      distMSTTokenRate: 22.5,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 6,
      weekAmount: 1500000000000,
      holdMST: 80000000000000000000000,
      commissionRate: 40,
      distMTokenRate: 20,
      distMSTTokenRate: 20,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 7,
      weekAmount: 800000000000,
      holdMST: 20000000000000000000000,
      commissionRate: 35,
      distMTokenRate: 17.5,
      distMSTTokenRate: 17.5,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 8,
      weekAmount: 400000000000,
      holdMST: 8000000000000000000000,
      commissionRate: 30,
      distMTokenRate: 15,
      distMSTTokenRate: 15,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 9,
      weekAmount: 100000000000,
      holdMST: 2000000000000000000000,
      commissionRate: 15,
      distMTokenRate: 0,
      distMSTTokenRate: 15,
      createdDate: new Date(),
    },
    {
      id: null,
      grade: 10,
      weekAmount: 0,
      holdMST: 0,
      commissionRate: 5,
      distMTokenRate: 0,
      distMSTTokenRate: 5,
      createdDate: new Date(),
    },
  ];

  const dummyMstPrices: MstPrice[] = [
    {
      mstPrice: '7152333',
      createdDate: new Date(),
      createdById: 1,
      lastModifiedDate: new Date(),
      lastModifiedById: 1,
      status: MstPriceStatus.StatusInactive,
    },
    {
      mstPrice: '9152333',
      createdDate: new Date(),
      createdById: 1,
      lastModifiedDate: new Date(),
      lastModifiedById: 1,
      status: MstPriceStatus.StatusActive,
    },
  ];

  //Insert------------------------
  //Agent

  //await modelModule[SeqModel.name.Agent].bulkCreate(dummyAgents);
  // await modelModule[SeqModel.name.Customer].bulkCreate(dummyCustomers);
  // await modelModule[SeqModel.name.CustomerCreditUpdate].bulkCreate(
  //   dummyCustomerCreditUpdates,
  // );

  // //DApp
  // await modelModule[SeqModel.name.Balance].bulkCreate(dummyBalances);
  // await modelModule[SeqModel.name.BalanceHistory].bulkCreate(
  //   dummyBalanceHistories,
  // );
  // await modelModule[SeqModel.name.PriceHistory].bulkCreate(dummyPriceHistories);
  // await modelModule[SeqModel.name.PriceHistoryRef].bulkCreate(
  //   dummyPRiceHistoriesRefs,
  // );
  // await modelModule[SeqModel.name.Stopout].bulkCreate(dummyStopouts);
  await modelModule[SeqModel.name.Transaction].bulkCreate(dummyTransactions);
  await modelModule[SeqModel.name.Prices].bulkCreate(dummyPrices);
  // await modelModule[SeqModel.name.AgentDailyReport].bulkCreate(
  //   dummyAgentDailyReports,
  // );

  await modelModule[SeqModel.name.Agent].bulkCreate(dummyAgents);
  await modelModule[SeqModel.name.Customer].bulkCreate(dummyCustomers);
  await modelModule[SeqModel.name.Token].bulkCreate(dummyTokens);
  await modelModule[SeqModel.name.CronJob].bulkCreate(dummyCronJobs);
  await modelModule[SeqModel.name.CommissionJob].bulkCreate(
    dummyCommissionJobs,
  );
  await modelModule[SeqModel.name.MSTDistRule].bulkCreate(dummyDistRuleMists);

  await modelModule[SeqModel.name.Balance].bulkCreate(dummyBalances);

  await modelModule[SeqModel.name.Agent].bulkCreate(dummyAgents2);
  await modelModule[SeqModel.name.Customer].bulkCreate(dummyCustomers2);
  // await modelModule[SeqModel.name.InterestHistory].bulkCreate(
  //   dummyInterestHistories,
  // );
  // await modelModule[SeqModel.name.InterestHistory].bulkCreate(
  //   dummyInterestHistoriesType2,
  // );
  await modelModule[SeqModel.name.Transaction].bulkCreate(
    dummyTransactionsType2,
  );

  await modelModule[SeqModel.name.MstPrice].bulkCreate(dummyMstPrices);

  // await modelModule[SeqModel.name.Price].bulkCreate(dummyPrice);
  /*


  await modelModule[SeqModel.name.CommissionLedger].bulkCreate(
    dummyCommissionLedgers,
  );
  await modelModule[SeqModel.name.CommissionSummary].bulkCreate(
    dummyCommissionSummaries,
  );
  await modelModule[SeqModel.name.CommissionDistribution].bulkCreate(
    dummyCommissionDistributions,
  );*/
  //console.log by css
  await createSqlFunction();
  // await modelModule[SeqModel.name.Transaction].bulkCreate(dummyTransactions);
  console.log(
    '%c ----- Done creating dummy table and data for DB! ----- ',
    'color:green',
  );
}
