import { AbiItem } from 'web3-utils';
const serviceConfigName = 'CronJobServerConfig';
const cronJobExpression = '0 0 0 * * ?';
const createdEventApi: AbiItem = {
  anonymous: false,
  inputs: [
    {
      indexed: false,
      internalType: 'uint256',
      name: 'roundID',
      type: 'uint256',
    },
    {
      indexed: false,
      internalType: 'address',
      name: 'creator',
      type: 'address',
    },
  ],
  name: 'Created',
  type: 'event',
};

const tempData = [
  {
    id: '1',
    node: '/1/',
    parentAgentId: null,
    agentType: 0,
    interestPercentage: '100',
    feePercentage: '100',
    name: '1',
    amount: '1000',
    accumalativeTxAmount: '68920',
    mstAmount: 0,
    commissionRate: 100,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: '2000',
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: '200',
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '1000',
        directFee: '3.000',
        directFeeIncome: '1.8',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '1000',
        directInterestIncome: '600',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '2',
    node: '/1/2/',
    parentAgentId: '1',
    agentType: 0,
    interestPercentage: '50',
    feePercentage: '50',
    name: '2',
    amount: '2000',
    accumalativeTxAmount: '23000',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: '500',
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: '50',
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '2000',
        directFee: '6.000',
        directFeeIncome: '3',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '2000',
        directInterestIncome: '1000',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '3',
    node: '/1/3/',
    parentAgentId: '1',
    agentType: 0,
    interestPercentage: '40',
    feePercentage: '40',
    name: '3',
    amount: '4000',
    accumalativeTxAmount: '10460',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '4000',
        directFee: '12.000',
        directFeeIncome: '4.8',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '4000',
        directInterestIncome: '1600',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '4',
    node: '/1/2/4/',
    parentAgentId: '2',
    agentType: 0,
    interestPercentage: '30',
    feePercentage: '30',
    name: '4',
    amount: '3000',
    accumalativeTxAmount: '8000',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '3000',
        directFee: '9.000',
        directFeeIncome: '2.7',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '3000',
        directInterestIncome: '900',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '5',
    node: '/1/2/5/',
    parentAgentId: '2',
    agentType: 0,
    interestPercentage: '30',
    feePercentage: '30',
    name: '5',
    amount: '6000',
    accumalativeTxAmount: '13000',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '6000',
        directFee: '18.000',
        directFeeIncome: '5.4',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '6000',
        directInterestIncome: '1800',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '6',
    node: '/1/2/4/6/',
    parentAgentId: '4',
    agentType: 0,
    interestPercentage: '20',
    feePercentage: '20',
    name: '6',
    amount: '5000',
    accumalativeTxAmount: '5000',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '5000',
        directFee: '15.000',
        directFeeIncome: '3',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '5000',
        directInterestIncome: '1000',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '7',
    node: '/1/2/5/7/',
    parentAgentId: '5',
    agentType: 0,
    interestPercentage: '20',
    feePercentage: '20',
    name: 'the verifier',
    amount: '7000',
    accumalativeTxAmount: '7000',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '7000',
        directFee: '21.000',
        directFeeIncome: '4.2',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '7000',
        directInterestIncome: '1400',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '8',
    node: '/1/3/8/',
    parentAgentId: '3',
    agentType: 0,
    interestPercentage: '40',
    feePercentage: '40',
    name: 'the verifier',
    amount: '390',
    accumalativeTxAmount: '5790',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '390',
        directFee: '1.170',
        directFeeIncome: '0.468',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '390',
        directInterestIncome: '156',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '9',
    node: '/1/3/9/',
    parentAgentId: '3',
    agentType: 0,
    interestPercentage: '30',
    feePercentage: '30',
    name: 'the verifier',
    amount: '120',
    accumalativeTxAmount: '670',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '120',
        directFee: '0.360',
        directFeeIncome: '0.108',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '120',
        directInterestIncome: '36',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '10',
    node: '/1/3/8/10/',
    parentAgentId: '8',
    agentType: 0,
    interestPercentage: '10',
    feePercentage: '10',
    name: 'the verifier',
    amount: '5400',
    accumalativeTxAmount: '5400',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '5400',
        directFee: '16.200',
        directFeeIncome: '1.62',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '5400',
        directInterestIncome: '540',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '11',
    node: '/1/3/9/11/',
    parentAgentId: '9',
    agentType: 0,
    interestPercentage: '20',
    feePercentage: '20',
    name: 'the verifier',
    amount: '550',
    accumalativeTxAmount: '550',
    mstAmount: 0,
    commissionRate: 0,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '550',
        directFee: '1.650',
        directFeeIncome: '0.33',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '550',
        directInterestIncome: '110',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '12',
    node: '/1/12/',
    parentAgentId: '1',
    agentType: 2,
    interestPercentage: 90,
    feePercentage: 90,
    name: 'the verifier',
    amount: '1000',
    accumalativeTxAmount: '34460',
    mstAmount: 10000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '1000',
        directFee: '3.000',
        directFeeIncome: '2.1',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '1000',
        directInterestIncome: '700',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '13',
    node: '/1/12/13/',
    parentAgentId: '12',
    agentType: 2,
    interestPercentage: 70,
    feePercentage: 70,
    name: 'the verifier',
    amount: '2000',
    accumalativeTxAmount: '23000',
    mstAmount: 5000000,
    commissionRate: 70,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '2000',
        directFee: '6.000',
        directFeeIncome: '3.6',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '2000',
        directInterestIncome: '1200',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '14',
    node: '/1/12/14/',
    parentAgentId: '12',
    agentType: 2,
    interestPercentage: 60,
    feePercentage: 60,
    name: 'the verifier',
    amount: '4000',
    accumalativeTxAmount: '10460',
    mstAmount: 1000000,
    commissionRate: 60,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '4000',
        directFee: '12.000',
        directFeeIncome: '7.2',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '4000',
        directInterestIncome: '2400',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '15',
    node: '/1/12/13/15/',
    parentAgentId: '13',
    agentType: 2,
    interestPercentage: 80,
    feePercentage: 80,
    name: 'the verifier',
    amount: '3000',
    accumalativeTxAmount: '8000',
    mstAmount: 10000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '3000',
        directFee: '9.000',
        directFeeIncome: '6.3',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '3000',
        directInterestIncome: '2100',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '16',
    node: '/1/12/13/16/',
    parentAgentId: '13',
    agentType: 2,
    interestPercentage: 30,
    feePercentage: 30,
    name: 'the verifier',
    amount: '6000',
    accumalativeTxAmount: '13000',
    mstAmount: 5000,
    commissionRate: 30,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '6000',
        directFee: '18.000',
        directFeeIncome: '10.8',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '6000',
        directInterestIncome: '3600',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '17',
    node: '/1/12/13/15/17/',
    parentAgentId: '15',
    agentType: 2,
    interestPercentage: 80,
    feePercentage: 80,
    name: 'the verifier',
    amount: '5000',
    accumalativeTxAmount: '5000',
    mstAmount: 1000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '5000',
        directFee: '15.000',
        directFeeIncome: '9',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '5000',
        directInterestIncome: '3000',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '18',
    node: '/1/12/13/16/18/',
    parentAgentId: '16',
    agentType: 2,
    interestPercentage: 52,
    feePercentage: 52,
    name: 'the verifier',
    amount: '7000',
    accumalativeTxAmount: '7000',
    mstAmount: 500000,
    commissionRate: 52,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '7000',
        directFee: '21.000',
        directFeeIncome: '12.6',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '7000',
        directInterestIncome: '4200',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '19',
    node: '/1/12/14/19/',
    parentAgentId: '14',
    agentType: 2,
    interestPercentage: 80,
    feePercentage: 80,
    name: 'the verifier',
    amount: '390',
    accumalativeTxAmount: '5790',
    mstAmount: 10000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '390',
        directFee: '1.170',
        directFeeIncome: '0.702',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '390',
        directInterestIncome: '234',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '20',
    node: '/1/12/14/20/',
    parentAgentId: '14',
    agentType: 2,
    interestPercentage: 80,
    feePercentage: 80,
    name: 'the verifier',
    amount: '120',
    accumalativeTxAmount: '670',
    mstAmount: 10000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '120',
        directFee: '0.360',
        directFeeIncome: '0.252',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '120',
        directInterestIncome: '84',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '21',
    node: '/1/12/14/19/21/',
    parentAgentId: '19',
    agentType: 2,
    interestPercentage: 80,
    feePercentage: 80,
    name: 'the verifier',
    amount: '5400',
    accumalativeTxAmount: '5400',
    mstAmount: 10000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '5400',
        directFee: '16.200',
        directFeeIncome: '11.34',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '5400',
        directInterestIncome: '3780',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  {
    id: '22',
    node: '/1/12/14/20/22/',
    parentAgentId: '20',
    agentType: 2,
    interestPercentage: 80,
    feePercentage: 80,
    name: 'the verifier',
    amount: '550',
    accumalativeTxAmount: '550',
    mstAmount: 10000000,
    commissionRate: 80,
    tokenAmts: [
      {
        token: 'BTCM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'ETHM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: 0,
        directFee: 0,
        directFeeIncome: 0,
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: 0,
        directInterestIncome: 0,
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
      {
        token: 'USDM',
        directUsedFee: 0,
        allSubAgentDirectUsedFee: 0,
        turnOver: '550',
        directFee: '1.650',
        directFeeIncome: '1.155',
        allSubAgentFee: 0,
        allSubAgentOwnedFee: 0,
        allSubAgentFeeIncome: 0,
        allChildAgentFeeIncome: 0,
        directInterest: '550',
        directInterestIncome: '385',
        allSubAgentInterest: 0,
        allSubAgentOwnedInterest: 0,
        allSubAgentInterestIncome: 0,
        allChildAgentInterestIncome: 0,
        feeIncome: 0,
        netFeeIncome: 0,
        netAgentFeeIncome: 0,
        interestIncome: 0,
        netInterestIncome: 0,
        netAgentInterestIncome: 0,
        totalIncome: 0,
      },
    ],
  },
  // {
  //   id: '23',
  //   node: '/1/12/14/20/22/',
  //   parentAgentId: '15',
  //   agentType: 2,
  //   interestPercentage: 30,
  //   feePercentage: 30,
  //   name: 'the verifier',
  //   amount: '550',
  //   accumalativeTxAmount: '550',
  //   mstAmount: 9845027,
  //   commissionRate: 30,
  //   tokenAmts: [
  //     {
  //       token: 'BTCM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'ETHM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'USDM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: '550',
  //       directFee: '1.650',
  //       directFeeIncome: '1.155',
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: '550',
  //       directInterestIncome: '385',
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //   ],
  // },
  // {
  //   id: '24',
  //   node: '/1/12/14/20/22/',
  //   parentAgentId: '23',
  //   agentType: 2,
  //   interestPercentage: 90,
  //   feePercentage: 90,
  //   name: 'the verifier',
  //   amount: '550',
  //   accumalativeTxAmount: '550',
  //   mstAmount: 9845027,
  //   commissionRate: 90,
  //   tokenAmts: [
  //     {
  //       token: 'BTCM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'ETHM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'USDM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: '550',
  //       directFee: '1.650',
  //       directFeeIncome: '1.155',
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: '550',
  //       directInterestIncome: '385',
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //   ],
  // },
  // {
  //   id: '25',
  //   node: '/1/12/14/20/22/',
  //   parentAgentId: '25',
  //   agentType: 2,
  //   interestPercentage: 70,
  //   feePercentage: 70,
  //   name: 'the verifier',
  //   amount: '550',
  //   accumalativeTxAmount: '550',
  //   mstAmount: 9845027,
  //   commissionRate: 70,
  //   tokenAmts: [
  //     {
  //       token: 'BTCM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'ETHM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'USDM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: '550',
  //       directFee: '1.650',
  //       directFeeIncome: '1.155',
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: '550',
  //       directInterestIncome: '385',
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //   ],
  // },
  // {
  //   id: '26',
  //   node: '/1/12/14/20/22/',
  //   parentAgentId: '15',
  //   agentType: 2,
  //   interestPercentage: 80,
  //   feePercentage: 80,
  //   name: 'the verifier',
  //   amount: '550',
  //   accumalativeTxAmount: '550',
  //   mstAmount: 9845027,
  //   commissionRate: 80,
  //   tokenAmts: [
  //     {
  //       token: 'BTCM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'ETHM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: 0,
  //       directFee: 0,
  //       directFeeIncome: 0,
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: 0,
  //       directInterestIncome: 0,
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //     {
  //       token: 'USDM',
  //       directUsedFee: 0,
  //       allSubAgentDirectUsedFee: 0,
  //       turnOver: '550',
  //       directFee: '1.650',
  //       directFeeIncome: '1.155',
  //       allSubAgentFee: 0,
  //       allSubAgentOwnedFee: 0,
  //       allSubAgentFeeIncome: 0,
  //       allChildAgentFeeIncome: 0,
  //       directInterest: '550',
  //       directInterestIncome: '385',
  //       allSubAgentInterest: 0,
  //       allSubAgentOwnedInterest: 0,
  //       allSubAgentInterestIncome: 0,
  //       allChildAgentInterestIncome: 0,
  //       feeIncome: 0,
  //       netFeeIncome: 0,
  //       netAgentFeeIncome: 0,
  //       interestIncome: 0,
  //       netInterestIncome: 0,
  //       netAgentInterestIncome: 0,
  //       totalIncome: 0,
  //     },
  //   ],
  // },
];
export { serviceConfigName, cronJobExpression, createdEventApi, tempData };
