/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IAgentData extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IAgentData;
  clone(): IAgentData;
  methods: {
    initialize(): NonPayableTransactionObject<void>;

    verifyData(
      agentAddr: string,
      data: string | number[]
    ): NonPayableTransactionObject<boolean>;

    insertData(
      agentAddr: string,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    updateData(
      agentAddr: string,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    approveData(
      agentAddr: string,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    getOwner(): NonPayableTransactionObject<string>;

    getInserters(): NonPayableTransactionObject<string[]>;

    getUpdaters(): NonPayableTransactionObject<string[]>;

    getApprovers(): NonPayableTransactionObject<string[]>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    grantInserter(inserterAddr: string): NonPayableTransactionObject<void>;

    grantUpdater(updaterAddr: string): NonPayableTransactionObject<void>;

    grantApprover(approverAddr: string): NonPayableTransactionObject<void>;

    revokeInserter(inserterAddr: string): NonPayableTransactionObject<void>;

    revokeUpdater(updaterAddr: string): NonPayableTransactionObject<void>;

    revokeApprover(approverAddr: string): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
